#-------------------------------#
#			Makefile			#
#-------------------------------#
#
#	cmd command is: make -f makefile
#
CC=g++
CFLAGS=-g -Wall -Wextra

main: main.cpp
	$(CC) $(CFLAGS) -o main main.cpp

clean:
	rm -f main